services:

  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - proxy

# ── Network ───────────────────────────────────────────────────────────────────
networks:
  proxy:
    external: true
    name: nfs-network